#!/bin/sh
#
# Compiles and installs all programs of the ui2go distribution.
#
go install github.com/yogischogi//ui2go/native
go install github.com/yogischogi//ui2go/event
go install github.com/yogischogi//ui2go/widget
go install github.com/yogischogi//ui2go/examples/01-window
go install github.com/yogischogi//ui2go/examples/02-paint
go install github.com/yogischogi//ui2go/examples/03-paint
go install github.com/yogischogi//ui2go/examples/04-imageviewer
go install github.com/yogischogi//ui2go/examples/05-layout-border
go install github.com/yogischogi//ui2go/examples/06-layout-grid
go install github.com/yogischogi//ui2go/examples/07-layout-inputmask
go install github.com/yogischogi//ui2go/examples/08-layout-complex
go install github.com/yogischogi//ui2go/examples/09-cap-test
go install github.com/yogischogi//ui2go/examples/10-widgetstyle
go install github.com/yogischogi//ui2go/examples/11-json-layout-border
